# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    # circle ci setup
    setup_circle_ci
  end

  lane :cert do
    match(type: 'appstore')
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: "66234AW2S2",
      issuer_id: "3df8377a-79a6-44b6-9194-f9bce53f1983",
      key_filepath: "./AuthKey_66234AW2S2.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    # increment_build_number(xcodeproj: "AwesomeTSProject.xcodeproj")
    build_app(workspace: "AwesomeTSProject.xcworkspace", scheme: "AwesomeTSProject")
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
    )
  end
end
